CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_USB_DEVICE_VID=0x4158
CONFIG_USB_DEVICE_PID=0x3635
CONFIG_USB_DEVICE_MANUFACTURER="Gzowski"
CONFIG_USB_DEVICE_PRODUCT="Shorky21"
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
